#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use App\App;
use App\Database;
use Database\Migrations\Migration;
use Database\Seeders\Seeder;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();
$dbConfig = require_once __DIR__ . '/config/database.php';

App::set(PDO::class, function () use ($dbConfig) {
  return Database::getPDO($dbConfig);
});

$db = App::get(PDO::class);

switch ($argv[1] ?? '') {
  case 'migrate':
    echo "migrating \n";
    App::get(Migration::class);
    echo "migrated\n";
    break;
    case 'seed':
      echo "migrating \n";
      App::get(Migration::class);
    echo 'migrated';
    echo "seeding \n";
    App::get(Seeder::class);
    echo 'done seeding';
    break;
  case 'serve':
    shell_exec('explorer http://localhost:8000');
    shell_exec('php -S localhost:8000 -t public');
    break;
}
flush();
exit();
?>